#! /usr/bin/env bash

tp="0 -1"
if [ $# -gt 0 ]; then
  tp=${1}
fi

#
# Use with care! *All* plots are closed by this command:
#
#killall /usr/bin/gnuplot 2>/dev/null

/usr/bin/gnuplot -p << EOF
set term wxt 0
set grid
set xlabel "Time [d]"
set ylabel "Conc. [pg/ml]"
a="E2"
plot for [k in "${tp}"] 'rb_Nlscon_with_PAEON_V2_solution.dat' i sprintf("== Iter %4s ==", k) u 1:a t sprintf("Iter %4s",k) w l lw 3, 'rb_Nlscon_with_PAEON_V2_data.dat' u 1:a t col w p pt 7 ps 0.6 lc rgb "blue"
#
set term wxt 1
set grid
set xlabel "Time [d]"
set ylabel "Conc. [ng/ml]"
a="P4"
plot for [k in "${tp}"] 'rb_Nlscon_with_PAEON_V2_solution.dat' i sprintf("== Iter %4s ==", k) u 1:a t sprintf("Iter %4s",k) w l lw 3, 'rb_Nlscon_with_PAEON_V2_data.dat' u 1:a t col w p pt 7 ps 0.6 lc rgb "blue"
#
set term wxt 2
set grid
set xlabel "Time [d]"
set ylabel "Conc. [mIU/ml]"
a="FSH_blood"
plot for [k in "${tp}"] 'rb_Nlscon_with_PAEON_V2_solution.dat' i sprintf("== Iter %4s ==", k) u 1:a t sprintf("Iter %4s",k) w l lw 3, 'rb_Nlscon_with_PAEON_V2_data.dat' u 1:a t col w p pt 7 ps 0.6 lc rgb "blue"
#
set term wxt 3 
set grid
set xlabel "Time [d]"
set ylabel "Conc. [mIU/ml]"
a="LH_blood"
plot for [k in "${tp}"] 'rb_Nlscon_with_PAEON_V2_solution.dat' i sprintf("== Iter %4s ==", k) u 1:a t sprintf("Iter %4s",k) w l lw 3, 'rb_Nlscon_with_PAEON_V2_data.dat' u 1:a t col w p pt 7 ps 0.6 lc rgb "blue"
EOF
